# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJBdSM_rndN9uTTP1uiPE7Gft7S4FGdb
"""

!pip -q install yfinance xgboost tensorflow scikit-learn pandas numpy matplotlib seaborn

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import yfinance as yf

from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from xgboost import XGBRegressor

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

from datetime import datetime

np.random.seed(42)
tf.random.set_seed(42)

# ==========================
# CONFIGURATION
# ==========================

LOOKBACK = 30

TRAIN_RATIO = 0.70
CALIBRATION_RATIO = 0.15
TEST_RATIO = 0.15

CONFIDENCE_LEVEL = 0.90

# Minimum requirements for allowing a model to make a prediction
MIN_DIRECTIONAL_ACCURACY = 0.52

# Require model to beat naive baseline by this much
MIN_IMPROVEMENT_OVER_NAIVE = 0.00

# Minimum historical data
MIN_ROWS = 750

print("TensorFlow:", tf.__version__)

TICKER = input("Enter stock ticker: ").upper().strip()

print(f"\nLoading {TICKER}...")

def download_data(ticker, period="max"):
    df = yf.download(
        ticker,
        period=period,
        interval="1d",
        auto_adjust=True,
        progress=False
    )

    if df.empty:
        raise ValueError(
            f"No data found for {ticker}. Check the ticker symbol."
        )

    # Handle yfinance multi-index columns
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    df = df.copy()

    required = ["Open", "High", "Low", "Close", "Volume"]

    for col in required:
        if col not in df.columns:
            raise ValueError(f"Missing column: {col}")

    df = df[required].dropna()

    return df


df = download_data(TICKER)

print(f"Downloaded {len(df):,} trading days")
print(f"From: {df.index.min().date()}")
print(f"To:   {df.index.max().date()}")

df.tail()

def create_features(df):

    data = df.copy()

    # -------------------------
    # Returns
    # -------------------------
    data["Return_1"] = np.log(
        data["Close"] / data["Close"].shift(1)
    )

    data["Return_5"] = np.log(
        data["Close"] / data["Close"].shift(5)
    )

    data["Return_20"] = np.log(
        data["Close"] / data["Close"].shift(20)
    )

    # -------------------------
    # Moving averages
    # -------------------------
    data["SMA_5"] = data["Close"].rolling(5).mean()
    data["SMA_10"] = data["Close"].rolling(10).mean()
    data["SMA_20"] = data["Close"].rolling(20).mean()
    data["SMA_50"] = data["Close"].rolling(50).mean()
    data["SMA_200"] = data["Close"].rolling(200).mean()

    data["Price_SMA20"] = data["Close"] / data["SMA_20"]
    data["Price_SMA50"] = data["Close"] / data["SMA_50"]
    data["Price_SMA200"] = data["Close"] / data["SMA_200"]

    # -------------------------
    # EMA
    # -------------------------
    data["EMA_12"] = data["Close"].ewm(span=12).mean()
    data["EMA_26"] = data["Close"].ewm(span=26).mean()

    data["MACD"] = data["EMA_12"] - data["EMA_26"]

    # -------------------------
    # Volatility
    # -------------------------
    data["Volatility_5"] = data["Return_1"].rolling(5).std()
    data["Volatility_20"] = data["Return_1"].rolling(20).std()
    data["Volatility_60"] = data["Return_1"].rolling(60).std()

    # -------------------------
    # RSI
    # -------------------------
    delta = data["Close"].diff()

    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.rolling(14).mean()
    avg_loss = loss.rolling(14).mean()

    rs = avg_gain / (avg_loss + 1e-10)

    data["RSI"] = 100 - (100 / (1 + rs))

    # -------------------------
    # Volume
    # -------------------------
    data["Volume_SMA20"] = data["Volume"].rolling(20).mean()

    data["Volume_Ratio"] = (
        data["Volume"] /
        (data["Volume_SMA20"] + 1e-10)
    )

    # -------------------------
    # High-low range
    # -------------------------
    data["Daily_Range"] = (
        data["High"] - data["Low"]
    ) / data["Close"]

    # -------------------------
    # Target = NEXT DAY return
    # -------------------------
    data["Target"] = np.log(
        data["Close"].shift(-1) / data["Close"]
    )

    data = data.replace([np.inf, -np.inf], np.nan)
    data = data.dropna()

    return data


data = create_features(df)

print("Feature dataset:", data.shape)

data.tail()

FEATURES = [
    "Return_1",
    "Return_5",
    "Return_20",

    "Price_SMA20",
    "Price_SMA50",
    "Price_SMA200",

    "MACD",

    "Volatility_5",
    "Volatility_20",
    "Volatility_60",

    "RSI",

    "Volume_Ratio",

    "Daily_Range"
]

X = data[FEATURES].copy()
y = data["Target"].copy()

print("Features:")
for f in FEATURES:
    print(" -", f)

print("\nSamples:", len(X))

n = len(data)

train_end = int(n * TRAIN_RATIO)
calibration_end = int(
    n * (TRAIN_RATIO + CALIBRATION_RATIO)
)

X_train = X.iloc[:train_end]
y_train = y.iloc[:train_end]

X_cal = X.iloc[train_end:calibration_end]
y_cal = y.iloc[train_end:calibration_end]

X_test = X.iloc[calibration_end:]
y_test = y.iloc[calibration_end:]

print("TRAIN:")
print(X_train.index.min().date(), "->", X_train.index.max().date())

print("\nCALIBRATION:")
print(X_cal.index.min().date(), "->", X_cal.index.max().date())

print("\nTEST:")
print(X_test.index.min().date(), "->", X_test.index.max().date())

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_cal_scaled = scaler.transform(X_cal)

X_test_scaled = scaler.transform(X_test)

print("Scaling complete.")

xgb_model = XGBRegressor(
    n_estimators=500,
    max_depth=5,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    eval_metric="rmse",
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(
    X_train,
    y_train,
    eval_set=[(X_cal, y_cal)],
    verbose=False
)

xgb_cal_pred = xgb_model.predict(X_cal)
xgb_test_pred = xgb_model.predict(X_test)

print("XGBoost trained.")

rf_model = RandomForestRegressor(
    n_estimators=500,
    max_depth=12,
    min_samples_leaf=5,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(
    X_train,
    y_train
)

rf_cal_pred = rf_model.predict(X_cal)
rf_test_pred = rf_model.predict(X_test)

print("Random Forest trained.")

def create_sequences(X_values, y_values, lookback):

    X_seq = []
    y_seq = []

    for i in range(lookback, len(X_values)):
        X_seq.append(
            X_values[i-lookback:i]
        )
        y_seq.append(
            y_values[i]
        )

    return np.array(X_seq), np.array(y_seq)


X_train_seq, y_train_seq = create_sequences(
    X_train_scaled,
    y_train.values,
    LOOKBACK
)

# For calibration/test we need the end of the preceding set
# so sequences retain their proper chronological history.

X_combined_cal = np.vstack([
    X_train_scaled[-LOOKBACK:],
    X_cal_scaled
])

y_combined_cal = np.concatenate([
    y_train.values[-LOOKBACK:],
    y_cal.values
])

X_cal_seq, y_cal_seq = create_sequences(
    X_combined_cal,
    y_combined_cal,
    LOOKBACK
)

X_combined_test = np.vstack([
    X_cal_scaled[-LOOKBACK:],
    X_test_scaled
])

y_combined_test = np.concatenate([
    y_cal.values[-LOOKBACK:],
    y_test.values
])

X_test_seq, y_test_seq = create_sequences(
    X_combined_test,
    y_combined_test,
    LOOKBACK
)

print("LSTM training shape:", X_train_seq.shape)
print("LSTM calibration shape:", X_cal_seq.shape)
print("LSTM test shape:", X_test_seq.shape)

def build_lstm(input_shape):

    model = Sequential([
        LSTM(
            64,
            return_sequences=True,
            input_shape=input_shape
        ),

        Dropout(0.20),

        LSTM(32),

        Dropout(0.20),

        Dense(16, activation="relu"),

        Dense(1)
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            learning_rate=0.001
        ),
        loss="mse"
    )

    return model


lstm_model = build_lstm(
    (
        X_train_seq.shape[1],
        X_train_seq.shape[2]
    )
)

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=15,
    restore_best_weights=True
)

history = lstm_model.fit(
    X_train_seq,
    y_train_seq,

    validation_data=(
        X_cal_seq,
        y_cal_seq
    ),

    epochs=100,
    batch_size=32,

    callbacks=[early_stop],

    verbose=1
)

lstm_cal_pred = lstm_model.predict(
    X_cal_seq,
    verbose=0
).flatten()

lstm_test_pred = lstm_model.predict(
    X_test_seq,
    verbose=0
).flatten()

print("LSTM trained.")

def evaluate_model(y_true, predictions, name):

    y_true = np.asarray(y_true)
    predictions = np.asarray(predictions)

    mae = mean_absolute_error(
        y_true,
        predictions
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_true,
            predictions
        )
    )

    r2 = r2_score(
        y_true,
        predictions
    )

    actual_direction = np.sign(y_true)

    predicted_direction = np.sign(predictions)

    directional_accuracy = np.mean(
        actual_direction == predicted_direction
    )

    return {
        "Model": name,
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2,
        "Directional_Accuracy": directional_accuracy
    }

# XGBoost / RF
results = []

results.append(
    evaluate_model(
        y_cal,
        xgb_cal_pred,
        "XGBoost"
    )
)

results.append(
    evaluate_model(
        y_cal,
        rf_cal_pred,
        "Random Forest"
    )
)

# LSTM
results.append(
    evaluate_model(
        y_cal_seq,
        lstm_cal_pred,
        "LSTM"
    )
)

results_df = pd.DataFrame(results)

print(results_df)

def conformal_interval(
    predictions,
    actuals,
    confidence=0.90
):

    predictions = np.asarray(predictions)
    actuals = np.asarray(actuals)

    residuals = np.abs(
        actuals - predictions
    )

    alpha = 1 - confidence

    q = np.quantile(
        residuals,
        1 - alpha
    )

    lower = predictions - q
    upper = predictions + q

    coverage = np.mean(
        (actuals >= lower) &
        (actuals <= upper)
    )

    avg_width = np.mean(
        upper - lower
    )

    return {
        "q": q,
        "coverage": coverage,
        "width": avg_width
    }

interval_results = []

models_predictions = {
    "XGBoost": (
        xgb_cal_pred,
        y_cal.values
    ),

    "Random Forest": (
        rf_cal_pred,
        y_cal.values
    ),

    "LSTM": (
        lstm_cal_pred,
        y_cal_seq
    )
}

for model_name, (pred, actual) in models_predictions.items():

    interval = conformal_interval(
        pred,
        actual,
        CONFIDENCE_LEVEL
    )

    interval_results.append({
        "Model": model_name,
        "Interval_Coverage": interval["coverage"],
        "Interval_Width": interval["width"],
        "Residual_Quantile": interval["q"]
    })


interval_df = pd.DataFrame(
    interval_results
)

results_df = results_df.merge(
    interval_df,
    on="Model"
)

results_df

def calculate_confidence_score(df):

    df = df.copy()

    # Normalize RMSE
    rmse_score = (
        1 -
        (
            df["RMSE"] /
            (df["RMSE"].max() + 1e-10)
        )
    )

    # Directional accuracy
    direction_score = df[
        "Directional_Accuracy"
    ]

    # R2 clipped to sensible range
    r2_score_component = (
        df["R2"].clip(-1, 1) + 1
    ) / 2

    # How close empirical coverage is to requested confidence
    coverage_score = 1 - (
        abs(
            df["Interval_Coverage"]
            - CONFIDENCE_LEVEL
        )
    )

    # Narrower interval gets a higher score
    width_score = (
        1 -
        (
            df["Interval_Width"] /
            (df["Interval_Width"].max() + 1e-10)
        )
    )

    df["Confidence_Score"] = (
        0.30 * rmse_score +
        0.25 * direction_score +
        0.15 * r2_score_component +
        0.20 * coverage_score +
        0.10 * width_score
    ) * 100

    return df


results_df = calculate_confidence_score(
    results_df
)

results_df = results_df.sort_values(
    "Confidence_Score",
    ascending=False
)

results_df

naive_test_pred = X_test["Return_1"].values

naive_results = evaluate_model(
    y_test.values,
    naive_test_pred,
    "Naive"
)

print(pd.DataFrame([naive_results]))

test_results = []

test_results.append(
    evaluate_model(
        y_test.values,
        xgb_test_pred,
        "XGBoost"
    )
)

test_results.append(
    evaluate_model(
        y_test.values,
        rf_test_pred,
        "Random Forest"
    )
)

test_results.append(
    evaluate_model(
        y_test_seq,
        lstm_test_pred,
        "LSTM"
    )
)

test_results_df = pd.DataFrame(
    test_results
)

test_results_df

naive_mae = naive_results["MAE"]

approved_models = []

for _, row in test_results_df.iterrows():

    model_name = row["Model"]

    beats_naive = (
        row["MAE"] <
        naive_mae *
        (1 - MIN_IMPROVEMENT_OVER_NAIVE)
    )

    directional_pass = (
        row["Directional_Accuracy"]
        >= MIN_DIRECTIONAL_ACCURACY
    )

    if beats_naive and directional_pass:
        approved_models.append(
            model_name
        )


print("Naive MAE:", naive_mae)

print("\nApproved models:")

if approved_models:
    for model in approved_models:
        print("✓", model)
else:
    print(
        "⚠ NONE — models did not meet "
        "the required historical accuracy."
    )

if len(approved_models) == 0:

    BEST_MODEL = None

    print(
        "\nNO MODEL APPROVED."
        "\nThe system will NOT make a prediction."
    )

else:

    eligible = results_df[
        results_df["Model"].isin(
            approved_models
        )
    ].copy()

    eligible = eligible.sort_values(
        "Confidence_Score",
        ascending=False
    )

    BEST_MODEL = eligible.iloc[0]["Model"]

    print(
        f"\n🏆 BEST MODEL: {BEST_MODEL}"
    )

    print(
        f"Confidence Score: "
        f"{eligible.iloc[0]['Confidence_Score']:.2f}/100"
    )

plt.figure(figsize=(12, 6))

sns.barplot(
    data=results_df,
    x="Model",
    y="Confidence_Score"
)

plt.axhline(
    50,
    color="red",
    linestyle="--",
    label="50"
)

plt.title(
    f"{TICKER} Model Confidence Score"
)

plt.ylabel("Confidence Score")
plt.legend()

plt.show()

def get_latest_features(data):

    latest = data[FEATURES].iloc[-1:].copy()

    return latest


latest_features = get_latest_features(data)

latest_scaled = scaler.transform(
    latest_features
)

xgb_next_return = xgb_model.predict(
    latest_features
)[0]

rf_next_return = rf_model.predict(
    latest_features
)[0]

# Need latest LOOKBACK observations

latest_lstm_input = scaler.transform(
    data[FEATURES].iloc[-LOOKBACK:]
)

latest_lstm_input = latest_lstm_input.reshape(
    1,
    LOOKBACK,
    len(FEATURES)
)

lstm_next_return = lstm_model.predict(
    latest_lstm_input,
    verbose=0
)[0][0]

predictions = {
    "XGBoost": xgb_next_return,
    "Random Forest": rf_next_return,
    "LSTM": lstm_next_return
}

if BEST_MODEL is None:

    print(
        "Prediction cancelled because "
        "no model passed the historical accuracy test."
    )

else:

    predicted_return = predictions[
        BEST_MODEL
    ]

    current_price = data["Close"].iloc[-1]

    predicted_price = (
        current_price *
        np.exp(predicted_return)
    )

    print("\n================================")
    print("STOCK PREDICTION")
    print("================================")

    print("Ticker:", TICKER)

    print(
        f"Current price: ${current_price:.2f}"
    )

    print(
        f"Predicted next-day return: "
        f"{predicted_return * 100:.3f}%"
    )

    print(
        f"Predicted price: "
        f"${predicted_price:.2f}"
    )

    print(
        f"Model: {BEST_MODEL}"
    )

if BEST_MODEL is not None:

    # Get calibration residuals for selected model

    if BEST_MODEL == "XGBoost":

        cal_predictions = xgb_cal_pred
        cal_actuals = y_cal.values

    elif BEST_MODEL == "Random Forest":

        cal_predictions = rf_cal_pred
        cal_actuals = y_cal.values

    elif BEST_MODEL == "LSTM":

        cal_predictions = lstm_cal_pred
        cal_actuals = y_cal_seq


    residuals = np.abs(
        cal_actuals -
        cal_predictions
    )

    interval_radius = np.quantile(
        residuals,
        CONFIDENCE_LEVEL
    )

    lower_return = (
        predicted_return -
        interval_radius
    )

    upper_return = (
        predicted_return +
        interval_radius
    )

    lower_price = (
        current_price *
        np.exp(lower_return)
    )

    upper_price = (
        current_price *
        np.exp(upper_return)
    )


    print("\n================================")
    print("90% PREDICTION INTERVAL")
    print("================================")

    print(
        f"Predicted price: "
        f"${predicted_price:.2f}"
    )

    print(
        f"Lower bound: "
        f"${lower_price:.2f}"
    )

    print(
        f"Upper bound: "
        f"${upper_price:.2f}"
    )

    print(
        f"Interval width: "
        f"${upper_price - lower_price:.2f}"
    )

if BEST_MODEL is not None:

    if predicted_return > 0.005:
        signal = "BULLISH"

    elif predicted_return < -0.005:
        signal = "BEARISH"

    else:
        signal = "NEUTRAL"


    confidence_row = results_df[
        results_df["Model"] == BEST_MODEL
    ].iloc[0]


    print("\n================================")
    print("FINAL SIGNAL")
    print("================================")

    print(f"Ticker:       {TICKER}")
    print(f"Signal:       {signal}")
    print(f"Model:        {BEST_MODEL}")

    print(
        f"Confidence:   "
        f"{confidence_row['Confidence_Score']:.1f}/100"
    )

    print(
        f"Historical directional accuracy: "
        f"{confidence_row['Directional_Accuracy']*100:.1f}%"
    )

    print(
        f"Historical interval coverage: "
        f"{confidence_row['Interval_Coverage']*100:.1f}%"
    )

    print(
        f"Predicted price: ${predicted_price:.2f}"
    )

    print(
        f"90% interval: "
        f"${lower_price:.2f} - ${upper_price:.2f}"
    )

plt.figure(figsize=(15, 7))

test_dates = y_test.index

plt.plot(
    test_dates,
    y_test.values,
    label="Actual Return",
    color="black"
)

plt.plot(
    test_dates,
    xgb_test_pred,
    label="XGBoost",
    alpha=0.8
)

plt.plot(
    test_dates,
    rf_test_pred,
    label="Random Forest",
    alpha=0.8
)

plt.plot(
    y_test_seq.index if hasattr(y_test_seq, "index")
    else test_dates[:len(lstm_test_pred)],
    lstm_test_pred,
    label="LSTM",
    alpha=0.8
)

plt.title(
    f"{TICKER} — Actual vs Model Predictions"
)

plt.xlabel("Date")
plt.ylabel("Next-Day Log Return")

plt.legend()
plt.grid(alpha=0.2)

plt.show()

CANDIDATE_TICKERS = [
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "GOOGL",
    "META",
    "AVGO",
    "TSLA",
    "NFLX",
    "AMD",
    "ORCL",
    "CRM",
    "ADBE",
    "COST",
    "WMT",
    "JPM",
    "V",
    "MA",
    "LLY",
    "UNH"
]

def scan_ticker(ticker):

    try:

        raw = download_data(ticker)

        if len(raw) < MIN_ROWS:
            return None

        d = create_features(raw)

        X = d[FEATURES]
        y = d["Target"]

        n = len(d)

        train_end = int(n * 0.70)
        cal_end = int(n * 0.85)

        X_train = X.iloc[:train_end]
        y_train = y.iloc[:train_end]

        X_cal = X.iloc[train_end:cal_end]
        y_cal = y.iloc[train_end:cal_end]

        X_test = X.iloc[cal_end:]
        y_test = y.iloc[cal_end:]

        model = XGBRegressor(
            n_estimators=400,
            max_depth=5,
            learning_rate=0.03,
            subsample=0.8,
            colsample_bytree=0.8,
            objective="reg:squarederror",
            random_state=42,
            n_jobs=-1
        )

        model.fit(
            X_train,
            y_train,
            eval_set=[(X_cal, y_cal)],
            verbose=False
        )

        cal_pred = model.predict(X_cal)
        test_pred = model.predict(X_test)

        mae = mean_absolute_error(
            y_test,
            test_pred
        )

        rmse = np.sqrt(
            mean_squared_error(
                y_test,
                test_pred
            )
        )

        direction = np.mean(
            np.sign(y_test.values)
            ==
            np.sign(test_pred)
        )

        residuals = np.abs(
            y_cal.values -
            cal_pred
        )

        interval_radius = np.quantile(
            residuals,
            CONFIDENCE_LEVEL
        )

        lower = test_pred - interval_radius
        upper = test_pred + interval_radius

        coverage = np.mean(
            (y_test.values >= lower) &
            (y_test.values <= upper)
        )

        current_price = d["Close"].iloc[-1]

        latest = X.iloc[-1:].copy()

        next_return = model.predict(
            latest
        )[0]

        next_price = (
            current_price *
            np.exp(next_return)
        )

        # Confidence score
        width = (
            upper - lower
        ).mean()

        score = (
            0.45 * direction +
            0.25 * coverage +
            0.20 * (1 / (1 + rmse)) +
            0.10 * (1 / (1 + width))
        ) * 100

        return {
            "Ticker": ticker,
            "Current_Price": current_price,
            "Predicted_Price": next_price,
            "Predicted_Return": next_return,
            "MAE": mae,
            "RMSE": rmse,
            "Directional_Accuracy": direction,
            "Interval_Coverage": coverage,
            "Interval_Width": width,
            "Confidence_Score": score
        }

    except Exception as e:

        print(
            f"{ticker}: ERROR -> {e}"
        )

        return None

scanner_results = []

print("Scanning companies...\n")

for ticker in CANDIDATE_TICKERS:

    print(
        f"Testing {ticker}..."
    )

    result = scan_ticker(ticker)

    if result is not None:
        scanner_results.append(result)


scanner_df = pd.DataFrame(
    scanner_results
)

scanner_df = scanner_df.sort_values(
    "Confidence_Score",
    ascending=False
)

scanner_df.head(10)

quality_companies = scanner_df[
    (
        scanner_df[
            "Directional_Accuracy"
        ] >= 0.52
    )
    &
    (
        scanner_df[
            "Interval_Coverage"
        ] >= 0.80
    )
].copy()

quality_companies = quality_companies.sort_values(
    "Confidence_Score",
    ascending=False
)

print(
    "\nTOP COMPANIES BY HISTORICAL MODEL QUALITY"
)

display(
    quality_companies[
        [
            "Ticker",
            "Current_Price",
            "Predicted_Price",
            "Predicted_Return",
            "Directional_Accuracy",
            "Interval_Coverage",
            "Confidence_Score"
        ]
    ].head(10)
)

print("\n==========================================")
print("TOP MODEL CANDIDATES")
print("==========================================")

for i, (_, row) in enumerate(
    quality_companies.head(10).iterrows(),
    start=1
):

    print(
        f"\n{i}. {row['Ticker']}"
    )

    print(
        f"   Confidence score: "
        f"{row['Confidence_Score']:.1f}/100"
    )

    print(
        f"   Directional accuracy: "
        f"{row['Directional_Accuracy']*100:.1f}%"
    )

    print(
        f"   90% interval coverage: "
        f"{row['Interval_Coverage']*100:.1f}%"
    )

    print(
        f"   Current: "
        f"${row['Current_Price']:.2f}"
    )

    print(
        f"   Prediction: "
        f"${row['Predicted_Price']:.2f}"
    )

    print(
        f"   Expected return: "
        f"{row['Predicted_Return']*100:.2f}%"
    )